package com.sajad.aideveloperagent.model;
import java.util.List;
/** Only these interpretive fields may be generated by a model. */
public record Analysis(String suspectedCause, List<String> recommendedChecks) {}
